// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZR843Z6l-FsZJiVgi1EgJfqst_d9Dre8',
    appId: '1:221699945611:web:656893fd3d920aebb9108e',
    messagingSenderId: '221699945611',
    projectId: 'yazlab-2-2-2929',
    authDomain: 'yazlab-2-2-2929.firebaseapp.com',
    storageBucket: 'yazlab-2-2-2929.appspot.com',
    measurementId: 'G-FEM84TQ5QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7G3hrWXce7xrJFCihqaxmLZfrf6kADs',
    appId: '1:221699945611:android:7f8b4de14f181df8b9108e',
    messagingSenderId: '221699945611',
    projectId: 'yazlab-2-2-2929',
    storageBucket: 'yazlab-2-2-2929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAIPc5N8iNKJDfFWi07EhVqsRrbhMzgM',
    appId: '1:221699945611:ios:f1c501c10306d123b9108e',
    messagingSenderId: '221699945611',
    projectId: 'yazlab-2-2-2929',
    storageBucket: 'yazlab-2-2-2929.appspot.com',
    iosBundleId: 'com.example.yazlab22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAIPc5N8iNKJDfFWi07EhVqsRrbhMzgM',
    appId: '1:221699945611:ios:d24bd817b6613452b9108e',
    messagingSenderId: '221699945611',
    projectId: 'yazlab-2-2-2929',
    storageBucket: 'yazlab-2-2-2929.appspot.com',
    iosBundleId: 'com.example.yazlab22.RunnerTests',
  );
}
